name = "GamersReforged"
author = "Den4enko"
version = "2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acf0ddf491dea61cc06b140524a46209fe73142c2a3c6bf5744ad43227a5be0c"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.1", "1.16.2", "1.16.3", "1.16.4"]
