name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13a9ed4f40d82a27137308c732fc295823fb854030353750dadda43208cbf106"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
