name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46369c29784d29a66c956314442606377ffe101e2a44e160958e38b999f7c6e5"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
