name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1335ba594461235be1424249bdd3217c2ed6c9993aa0037b612214c1a02fdc89"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
