name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "030f26ad84f483733882811948444086615ce5aafed382186c293f531cfed919"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
