name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ebc3b4044e10526bf95fc0c2478ef3439d52357e8076515a1ff469be58c6852"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
