name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "085787b1f957f4c3ea1b42dabd03ad9e16f7c2b1aec51d393b07f893701a06b0"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
