name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0736b2a63a922a62046c07cd33abe1be44830e30b23eb4391ac42732a160cd76"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
