name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47f1bc18ce0a657afa5a20396747957890d8b1386a10c9d968e9c49e8b5a37c4"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
