name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fd5f35340b7febc27deefff4ff625c2429213cfa198b72b3ffb9302d030335f"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
