name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "428017e0a803beafc6956b6be21d72c74f95393c7bc851592d285713cb45f39a"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
