name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "057e79c6cdc488c26d91840d3aff70cae1246eb96d6d5e2168489e45eb433211"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.1", "1.16.2", "1.16.3", "1.16.4"]
