name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "630d87d3a995669f271554e12ddc5d485a088e20b17bb2f8c2795669f89d635a"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
