name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2712c49e31da5fa4d6edc9ba9bdf064322db86b9e7a4aa9e2962d4e47b85949"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
