name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d63bfbfbad7a4e3a76d67becb959d2c57644e0ef3eb98922db76abae844d566e"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
