name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc11f32350b2bcf6ea6e15a1b843654ec02109fbc3674b38e86d08274f5c37b9"

[versions]
forge = "36.2.29"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.1", "1.16.2", "1.16.3", "1.16.4"]
