name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d905afb87b83dbc79c76f6beb201d85b88271127d3d3b9d53bf7a0036ded4963"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
