name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42d9a1c804de75d40b6b381d5c23044e9ea73b4e2bfeaf064eb73a2387955266"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
