name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf0c3e3e5b828c33689342b4dbca0ad932b6890ea4daa0423eb71c5fdc55b93b"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
