name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aba23d28140b0cca82e51ab9cc9eaf34118e3d1ef728f3bdcdda767f3dd3b0e3"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
