name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5eb01230e370c02e82e46e475b3cec375db9ad92983854cbf987b4b66109fbe"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
