name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24fa81ffd14d6a3af1d9f90f2f7c01140978f18dc11ae518dbe348155025661d"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
