name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "520d296a6cfad74ebd937ec122e0befb7fb1805309e324d2726f2f80a8226eda"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
