name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66a571d29393631c1d6a00452bc5e1f37c9f306ca97848bf0fe8d29d39cf47ed"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
