name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b71e1b63983fe5fc0d780db809eb583cc3af7844d9766f95a6c1cb9d2e2e4bf7"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
