name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fceede9a02dc4908711f9a4915224eaa253f4822ec0a6d39f8e1508158dbb7d2"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
