name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de64aa79c4c1822cd4199f0caad3d16223e02af4c146a4785fe6f4b59fbd4452"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
