name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e2205301c57dbd935499809b081cce2cd3bd42ab5e3c2eed268f8ecce3f400b"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
