name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8509f99b075a483724687b490e0d5f6573aba54207f72bb4f36422d115b2585"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
