name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cbc5bd68b329da7fa44f9190d71d32ff0a113f123e3f088d6c6584c55d013a1"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
