name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98aea9636f5868996ff56c2656e4f3d0b3a7ab99810d774a6293991c19acea29"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
