name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04e0f8216cd329f6c00dbab8fd00dd8a2644d559d1fe3962ee09c5946753d862"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
