name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c83ee1e0583d9e62e203afb6dde64f4df424e5cab601fab6ac09e50f285a5535"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
