name = "GamersReforged"
author = "Den4enko"
version = "SNAPSHOT"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f80589ed0ff6ad0625e8c0d5db086dfef41873f07f10661fc3d3376e9d6369f7"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
