name = "GamersReforged"
author = "Den4enko"
version = "1.9"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb3a5fa576c60c56b2ab50f818a9acc239ee4a31576e2ce1f8f02ac77f8e639e"

[versions]
forge = "36.2.23"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.1", "1.16.2", "1.16.3", "1.16.4"]
