name = "GamersReforged"
author = "Den4enko"
version = "1.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fe15f7572285026e37bbb949cff82247f9d37ca5cde01e54a40de89fc874884"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
