name = "GamersReforged"
author = "Den4enko"
version = "1.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8804634e43bf568569809b2d37e6592238e8f3b6f4c859bc2f49e95bf09d8c83"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
