name = "GamersReforged"
author = "Den4enko"
version = "1.3.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e94977445cbcf742ed2e2a49a804aacb673fd28f5bdbe583950fc70e3d96983f"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
