name = "GamersReforged"
author = "Den4enko"
version = "1.9"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31854c712e1094f8dcdfe935d1ae0aec9a81b18fc1597a9b1466cb05ca86ab3a"

[versions]
forge = "36.2.23"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.1", "1.16.2", "1.16.3", "1.16.4"]
