name = "GamersReforged"
author = "Den4enko"
version = "1.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37a5f280ad19cf07fff32309006e7c2c14a57d991e044a427c6b1fbad7e17c1e"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
