name = "GamersReforged"
author = "Den4enko"
version = "1.9.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07a85ec05b5cc385fb60237fd0b0603b6ef42adb2e7a1ab103ec68cb175192c6"

[versions]
forge = "36.2.26"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.1", "1.16.2", "1.16.3", "1.16.4"]
