name = "GamersReforged"
author = "Den4enko"
version = "1.7"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "022f9cb11167b902b85cf8bf5247e5568d49bca696e0f17edbee56a523b944a5"

[versions]
forge = "36.2.23"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.1", "1.16.2", "1.16.3", "1.16.4"]
