name = "GamersReforged"
author = "Den4enko"
version = "1.4.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "828c1f2c1b11d2f7292728499fb2a961979ed77b4f3167fd5d88bf505c3c47e6"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
