name = "GamersReforged"
author = "Den4enko"
version = "1.10"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c5b24c80f25e8b397b892ecaef5590b32b1650e08e256b9de4fcd01c8121883"

[versions]
forge = "36.2.26"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.1", "1.16.2", "1.16.3", "1.16.4"]
