name = "GamersReforged"
author = "Den4enko"
version = "1.6.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35a2772e270a36f335367a993e27c28055904f1dc5ba7485938c2b42696ece64"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.1", "1.16.2", "1.16.3", "1.16.4"]
