name = "GamersReforged"
author = "Den4enko"
version = "1.9.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1753149ebf385069fed3fe9a18b13aa75bd74ae40542fefcf83518a95a2c0ab"

[versions]
forge = "36.2.23"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.1", "1.16.2", "1.16.3", "1.16.4"]
