name = "GamersReforged"
author = "Den4enko"
version = "1.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12201c4158680b833ed256ae15cbb0f0cf094346b2cf940a017b71786f3738e3"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
