name = "GamersReforged"
author = "Den4enko"
version = "1.6.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "157c5f6c74625de54ac9eed243cd79876ded3abdc5858781ddda6ed55a46a06f"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.1", "1.16.2", "1.16.3", "1.16.4"]
