name = "GamersReforged"
author = "Den4enko"
version = "1.7"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11f6634761c18f1333ef25e869747f7728657cf377f955927ff5dddea116e9c4"

[versions]
forge = "36.2.23"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.1", "1.16.2", "1.16.3", "1.16.4"]
