name = "GamersReforged"
author = "Den4enko"
version = "1.5.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6401e29af2d37dec86d8c635f7552c48e662b73eda69ed929b4b70fc97835829"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
