name = "GamersReforged"
author = "Den4enko"
version = "1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9dfdb2172146974ce1b223fe1a92e246e39582e6e2362e84084f82a23bea4e7"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
