name = "GeckoLib"
filename = "geckolib-forge-1.16.5-3.0.74.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "f5b2ea848904862d653f7817cab59c7d95c5d00d"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3819094
project-id = 388172
