name = "MineColonies"
filename = "minecolonies-1.16.5-1.0.779-ALPHA.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "a98551594cff700fa30c203ba4972556e8034f56"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3810953
project-id = 245506
