name = "More Mekanism Processing"
filename = "MoreMekanismProcessing-1.16.5-1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3776/979/MoreMekanismProcessing-1.16.5-1.4.jar"
hash-format = "sha1"
hash = "9f31f1d55b94cdce3c71b51375e20822d64f4c7f"

[update]
[update.curseforge]
file-id = 3776979
project-id = 511965
