name = "Project MMO"
filename = "Project_MMO-1.16.5-3.67.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3735/196/Project_MMO-1.16.5-3.67.6.jar"
hash-format = "sha1"
hash = "56f4aa88c7501380440bb806a5665c7d6dc9a58d"

[update]
[update.curseforge]
file-id = 3735196
project-id = 353935
