name = "SuperMartijn642's Config Lib"
filename = "supermartijn642configlib-1.1.0-forge-mc1.16.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "202801a4ba48358d651a74338e457ab315911334"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3819626
project-id = 438332
