name = "The Legend of Herobrine (Forge 1.16.5)"
filename = "TheLegendOfHerobrine-1.16.5-0.6.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3424/369/TheLegendOfHerobrine-1.16.5-0.6.3.jar"
hash-format = "murmur2"
hash = "3755599714"

[update]
[update.curseforge]
file-id = 3424369
project-id = 355910
